"""
extract_phi3_mini_answers.py
────────────────────────────
Scan all phi3:mini baseline result files under data/eval/baselines/
(including the ash/ subdirectory) and extract every model_response answer
generated by the phi3:mini model.

Deduplication is performed by record `id` — if the same question id appears
in multiple checkpoint files, only the entry from the *latest* file
(determined by filename sort order) is kept, ensuring the most up-to-date
response wins.

Output file: data/eval/baselines/phi3_mini_answers.json

Usage:
    python scripts/extract_phi3_mini_answers.py
    python scripts/extract_phi3_mini_answers.py --input-dir data/eval/baselines --output data/eval/baselines/phi3_mini_answers.json

Output schema (one object per unique question):
    {
        "index":          <int>    — 1-based position in the final list,
        "id":             <str>    — original record id,
        "layer":          <int>    — source layer number,
        "category":       <str>    — clinical category tag,
        "source":         <str>    — source document / dataset name,
        "question":       <str>    — the question posed to the model,
        "model_response": <str>    — the phi3:mini generated answer,
        "gold_answer":    <str>    — reference / gold-standard answer,
        "score":          <int|null> — assigned score (if any),
        "max_score":      <int>    — maximum possible score,
        "model":          <str>    — model identifier ("phi3:mini")
    }
"""

import argparse
import json
import os
import sys
from pathlib import Path

# ── constants ─────────────────────────────────────────────────────────────────
TARGET_MODEL: str = "phi3:mini"
DEFAULT_INPUT_DIR: str = "data/eval/baselines"
DEFAULT_OUTPUT: str = "data/eval/baselines/phi3_mini_answers.json"

# Fields that must be present in every record for it to be considered valid
REQUIRED_FIELDS: tuple[str, ...] = ("id", "model_response")


# ── discovery ─────────────────────────────────────────────────────────────────
def discover_json_files(input_dir: Path) -> list[Path]:
    """
    Recursively find all *.json files under *input_dir*.

    Files are returned in ascending filename order so that later checkpoints
    (which sort higher alphabetically) overwrite earlier ones when
    deduplicating by record id.

    Args:
        input_dir: Root directory to search.

    Returns:
        Sorted list of Path objects pointing to every JSON file found.

    Raises:
        FileNotFoundError: If *input_dir* does not exist.
    """
    if not input_dir.is_dir():
        raise FileNotFoundError(
            f"Input directory not found: {input_dir.resolve()}"
        )

    json_files = sorted(input_dir.rglob("*.json"))

    if not json_files:
        raise FileNotFoundError(
            f"No JSON files found under: {input_dir.resolve()}"
        )

    return json_files


# ── validation ────────────────────────────────────────────────────────────────
def validate_record(record: object, filepath: Path, idx: int) -> bool:
    """
    Check whether a single record is a valid phi3:mini answer entry.

    A record is considered valid when:
      - It is a dict.
      - It contains all REQUIRED_FIELDS.
      - The model_response value is a non-empty string.

    Args:
        record:   The parsed JSON object representing one record.
        filepath: Source file path (used for warning messages only).
        idx:      Zero-based index of the record within its file.

    Returns:
        True if the record passes all checks, False otherwise.
    """
    if not isinstance(record, dict):
        print(
            f"  [WARN] Non-dict entry at index {idx} in {filepath.name} — skipped.",
            file=sys.stderr,
        )
        return False

    for field in REQUIRED_FIELDS:
        if field not in record:
            print(
                f"  [WARN] Missing '{field}' at index {idx} in {filepath.name} — skipped.",
                file=sys.stderr,
            )
            return False

    if not isinstance(record["model_response"], str) or not record["model_response"].strip():
        print(
            f"  [WARN] Empty model_response at index {idx} in {filepath.name} — skipped.",
            file=sys.stderr,
        )
        return False

    return True


# ── extraction ────────────────────────────────────────────────────────────────
def load_records_from_file(filepath: Path) -> list[dict]:
    """
    Parse a single JSON file and return its records as a list of dicts.

    Handles two valid top-level structures:
      - A JSON array  (e.g. ``[{...}, {...}]``)
      - A wrapped dict with a ``"fullContent"`` key (e.g. ``{"fullContent": [...]}``).

    Args:
        filepath: Absolute or relative path to the JSON file.

    Returns:
        List of raw record dicts (may be empty).

    Raises:
        json.JSONDecodeError: If the file is not valid JSON.
        ValueError: If the top-level structure is not recognised.
    """
    with open(filepath, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    if isinstance(data, list):
        return data
    if isinstance(data, dict) and "fullContent" in data:
        return data["fullContent"]

    raise ValueError(
        f"Unexpected JSON structure in {filepath}: "
        "expected a top-level array or {\"fullContent\": [...]}."
    )


def is_phi3_mini_record(record: dict) -> bool:
    """
    Determine whether a record was generated by the phi3:mini model.

    Detection strategy (in priority order):
      1. Explicit ``"model"`` field equals TARGET_MODEL.
      2. No ``"model"`` field present — the file is assumed to contain only
         phi3:mini results (legacy checkpoint files lack a model tag).

    Args:
        record: A parsed record dict.

    Returns:
        True if the record should be attributed to phi3:mini, False otherwise.
    """
    model_field = record.get("model", "").strip().lower()
    target = TARGET_MODEL.lower()

    # Explicit match
    if model_field == target:
        return True

    # No model tag — assume it belongs to phi3:mini (legacy files)
    if not model_field:
        return True

    return False


def extract_answer_entry(record: dict) -> dict:
    """
    Build a clean answer entry dict from a raw record.

    Only the fields relevant for analysis and review are carried over.
    Any field absent in the source record defaults to an empty string or None.

    Args:
        record: A validated raw record dict.

    Returns:
        A normalised dict ready for the output file.
    """
    return {
        "id":             record["id"],
        "layer":          record.get("layer"),
        "category":       record.get("category", ""),
        "source":         record.get("source", ""),
        "question":       record.get("question", ""),
        "model_response": record["model_response"].strip(),
        "gold_answer":    record.get("gold_answer", ""),
        "score":          record.get("score"),
        "max_score":      record.get("max_score"),
        "model":          TARGET_MODEL,
    }


# ── output ────────────────────────────────────────────────────────────────────
def write_output(answers: list[dict], output_path: Path) -> None:
    """
    Write the deduplicated answer list to a JSON file.

    Each entry is annotated with a 1-based ``index`` field.
    The output directory is created automatically if it does not exist.

    Args:
        answers:     List of extracted answer dicts (already deduplicated).
        output_path: Destination file path for the JSON output.

    Raises:
        OSError: If the output file cannot be written.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    annotated = [{"index": i + 1, **entry} for i, entry in enumerate(answers)]

    with open(output_path, "w", encoding="utf-8") as fh:
        json.dump(annotated, fh, indent=2, ensure_ascii=False)


# ── summary ───────────────────────────────────────────────────────────────────
def print_summary(
    files_scanned: int,
    total_seen: int,
    duplicates_dropped: int,
    final_count: int,
    output_path: Path,
) -> None:
    """
    Print a human-readable extraction summary to stdout.

    Args:
        files_scanned:      Number of JSON files processed.
        total_seen:         Total phi3:mini records encountered across all files.
        duplicates_dropped: Number of records removed as duplicates.
        final_count:        Number of unique records in the output file.
        output_path:        Path where the output file was written.
    """
    sep = "-" * 60
    print(f"\n{sep}")
    print("  PHI3:MINI ANSWER EXTRACTION SUMMARY")
    print(sep)
    print(f"  Files scanned      : {files_scanned:>6}")
    print(f"  Records found      : {total_seen:>6}")
    print(f"  Duplicates dropped : {duplicates_dropped:>6}")
    print(f"  Unique answers     : {final_count:>6}")
    print(sep)
    print(f"  Output             : {output_path.resolve()}")
    print(f"{sep}\n")


# ── main ──────────────────────────────────────────────────────────────────────
def main() -> None:
    """
    Entry point: parse arguments, discover files, extract answers, write output.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Extract all phi3:mini model_response answers from baseline JSON "
            "files, deduplicate by question id, and write to "
            "phi3_mini_answers.json."
        )
    )
    parser.add_argument(
        "--input-dir",
        default=DEFAULT_INPUT_DIR,
        help=f"Root directory containing baseline JSON files (default: {DEFAULT_INPUT_DIR})",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Output file path (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_path = Path(args.output)

    print(f"\n  Model   : {TARGET_MODEL}")
    print(f"  Input   : {input_dir.resolve()}")
    print(f"  Output  : {output_path.resolve()}\n")

    # ── discover files ────────────────────────────────────────────────────────
    try:
        json_files = discover_json_files(input_dir)
    except FileNotFoundError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"  Found {len(json_files)} JSON file(s) to scan.\n")

    # ── extract and deduplicate ───────────────────────────────────────────────
    # Ordered dict preserves insertion order; later files overwrite earlier ones
    # so that the newest response wins for each duplicate id.
    seen: dict[str, dict] = {}
    total_seen: int = 0
    files_scanned: int = 0

    for filepath in json_files:
        print(f"  [+] Scanning {filepath.name} ...", end=" ", flush=True)

        try:
            raw_records = load_records_from_file(filepath)
        except (json.JSONDecodeError, ValueError) as exc:
            print(f"\n  [!] Parse error — {exc} — skipped.", file=sys.stderr)
            continue

        file_count = 0
        for idx, record in enumerate(raw_records):
            if not validate_record(record, filepath, idx):
                continue
            if not is_phi3_mini_record(record):
                continue

            entry = extract_answer_entry(record)
            record_id = entry["id"]

            if record_id in seen:
                # Overwrite with the newer file's version
                seen[record_id] = entry
            else:
                seen[record_id] = entry

            total_seen += 1
            file_count += 1

        files_scanned += 1
        print(f"{file_count} phi3:mini record(s)")

    # ── guard: nothing extracted ──────────────────────────────────────────────
    if not seen:
        print(
            "\n[ERROR] No phi3:mini answers were extracted. "
            "Check that the input directory contains valid baseline files.",
            file=sys.stderr,
        )
        sys.exit(1)

    unique_answers = list(seen.values())
    duplicates_dropped = total_seen - len(unique_answers)

    # ── write output ──────────────────────────────────────────────────────────
    try:
        write_output(unique_answers, output_path)
    except OSError as exc:
        print(f"\n[ERROR] Failed to write output: {exc}", file=sys.stderr)
        sys.exit(1)

    # ── summary ───────────────────────────────────────────────────────────────
    print_summary(
        files_scanned=files_scanned,
        total_seen=total_seen,
        duplicates_dropped=duplicates_dropped,
        final_count=len(unique_answers),
        output_path=output_path,
    )


if __name__ == "__main__":
    main()
